DELETE FROM "Recipe_Tag" CASCADE;
DELETE FROM "User_Liked_Recipe" CASCADE;
DELETE FROM "Recipe_Ingredient" CASCADE;
DELETE FROM "Recipe" CASCADE;
DELETE FROM "Ingredient" CASCADE;
DELETE FROM "User" CASCADE;
DELETE FROM "Tag" CASCADE;
DELETE FROM "User_Role" CASCADE;