DROP TABLE "Recipe" CASCADE;
DROP TABLE "Ingredient" CASCADE;
DROP TABLE "Recipe_Ingredient" CASCADE;
DROP TABLE "User" CASCADE;
DROP TABLE "User_Role" CASCADE;
DROP TABLE "User_Liked_Recipe" CASCADE;
DROP TABLE "Tag" CASCADE;
DROP TABLE "Recipe_Tag" CASCADE;